version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/dev/dreaminsight"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
  - package-ecosystem: "github-actions"
    directory: "/dev/dreaminsight"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"

