import type { SymbolMeaning } from "./core";

// Auto-generated or manually curated additional symbols for encyclopedia growth.
// You can regenerate this file via scripts/import-dict.ts from CSV.

export const IMPORTED_SYMBOLS: Record<string, SymbolMeaning> = {
  elevator: {
    key: 'elevator', label: '엘리베이터', tags: ['전환','상승','통제'],
    meaning: '빠른 전환/상승·하강의 상징. 버튼/정지/추락 감각은 통제와 직결.',
    advice: '한 단계 전환을 위한 준비 1가지를 체크하고 버튼을 누르듯 실행하세요.',
    contexts: { psych: '외부 시스템 의존(엘리베이터) 대 내부 노력(계단)의 대비.' }
  },
  stairs: {
    key: 'stairs', label: '계단', tags: ['성장','노력','피로'],
    meaning: '계단은 점진적 성장과 그 과정의 피로를 상징.',
    advice: '다음 한 칸(작업 1조각)만 집중해 완료하세요.',
  },
  toilet: {
    key: 'toilet', label: '화장실', tags: ['정화','배출','지연'],
    meaning: '감정/과제 배출의 지연 또는 사생활/경계 이슈.',
    advice: '미완료 항목 1개를 “보류/아니오”로 명확화하세요.',
  },
  mirror: {
    key: 'mirror', label: '거울', tags: ['자아상','정체성'],
    meaning: '자기 인식/자아상 점검의 상징.',
    advice: '자기서술 3문장(나는 … 사람이다)을 적어보세요.',
  },
  hair_loss: {
    key: 'hair_loss', label: '머리카락 빠짐', tags: ['에너지','자존감'],
    meaning: '활력 고갈·자존감 저하 시그널.',
    advice: '수면/영양/움직임 중 1가지를 10분 보강하세요.',
  },
  baby: {
    key: 'baby', label: '아기/아이', tags: ['새 시작','보호','성장'],
    meaning: '미성숙한 가능성/새 프로젝트의 씨앗.',
    advice: '작은 프로젝트 씨앗에 이름을 붙이고 10분 스케치.',
  },
  dog_bite: {
    key: 'dog_bite', label: '개에게 물림', tags: ['경계','충성','공격성'],
    meaning: '경계/충성/공격성 테마의 충돌.',
    advice: '경계선 선언 문장 1개를 작성하세요.',
  },
  snake_skin: {
    key: 'snake_skin', label: '뱀/탈피', tags: ['변화','재생','경고'],
    meaning: '변신/탈피 욕구와 동반되는 불안.',
    advice: '버릴 것 1개를 정하고 실제로 버리세요.',
  },
  earthquake: {
    key: 'earthquake', label: '지진/붕괴', tags: ['기반','불안','경고'],
    meaning: '기초 구조 흔들림(건강/재정/관계)의 감지.',
    advice: '핵심 기반 3항목(건강/재정/관계)을 점검하세요.',
  },
  blood_signal: {
    key: 'blood_signal', label: '피/빨강', tags: ['에너지','경고'],
    meaning: '강렬한 에너지/경고의 혼합 신호.',
    advice: '무리한 일정/관계 1건을 오늘 피하세요.',
  },
  heavy_rain: {
    key: 'heavy_rain', label: '비/폭우', tags: ['감정','정화'],
    meaning: '감정 과잉/정화 필요.',
    advice: '물리적 정리 10분 + 짧은 샤워로 리셋.',
  },
  snow_white: {
    key: 'snow_white', label: '눈/하양', tags: ['정화','정지','차분'],
    meaning: '정화/정지/차분의 상징.',
    advice: '속도를 낮추고 알림을 1시간 꺼두세요.',
  },
  school_late: {
    key: 'school_late', label: '학교/지각', tags: ['평가','기대','압박'],
    meaning: '평가/기대에 대한 압박.',
    advice: '최소 완성 정의를 다시 설정하세요.',
  },
  airport_passport: {
    key: 'airport_passport', label: '공항/여권', tags: ['전환','자격','불안'],
    meaning: '전환/새 단계 진입 욕구와 자격 불안.',
    advice: '필수 요건 체크리스트 3개를 확인하세요.',
  },
  stage_speech: {
    key: 'stage_speech', label: '무대/발표', tags: ['표현','평가','긴장'],
    meaning: '표현/평가 상황의 긴장을 반영. 준비도와 자기 효능감 이슈.',
    advice: '핵심 메시지 1문장과 근거 2개로 3분 리허설.',
  },
  naked_public: {
    key: 'naked_public', label: '공공장소에서 벌거벗음', tags: ['수치','노출','경계'],
    meaning: '경계 약화/사생활 노출 불안.',
    advice: '경계선 1가지를 명확히 하고 오늘 선언하세요.',
  },
  brake_fail: {
    key: 'brake_fail', label: '브레이크 고장', tags: ['통제상실','불안','위험'],
    meaning: '속도/강도 조절 실패에 대한 불안.',
    advice: '일정 20% 감축 + 중단 기준 1줄 설정.',
  },
  car_drive: {
    key: 'car_drive', label: '자동차/운전', tags: ['방향성','통제','여정'],
    meaning: '방향성/통제감에 대한 점검 신호.',
    advice: '이번 주 경로/우선순위 3줄로 재정의.',
  },
  bus_miss: {
    key: 'bus_miss', label: '버스/기회를 놓침', tags: ['타이밍','집단','후회'],
    meaning: '타이밍 미스/집단 리듬과의 불일치.',
    advice: '다음 기회 알림/리마인더 1개 설정.',
  },
  train_trip: {
    key: 'train_trip', label: '기차 여행', tags: ['과정','리듬','전환'],
    meaning: '정해진 레일 위의 전환/과정 수용.',
    advice: '과정의 이점 3개 기록하고 속도 조정.',
  },
  storm_thunder: {
    key: 'storm_thunder', label: '폭풍/천둥', tags: ['감정폭발','정화','긴장'],
    meaning: '감정의 급격한 방출과 정화 필요.',
    advice: '감정 라벨링 3문장 + 4-7-8 호흡 3회.',
  },
  fire: {
    key: 'fire', label: '불/화재', tags: ['에너지','파괴','변화'],
    meaning: '강렬한 에너지/변화의 양면성.',
    advice: '충동 행동 10초 멈춤, 에너지 방향 전환 1건.',
  },
  flood: {
    key: 'flood', label: '홍수', tags: ['감정과잉','압도','정화'],
    meaning: '감정/자극의 과잉으로 압도된 상태.',
    advice: '자극 차단 25분(알림 off) + 물 한 잔.',
  },
  exam_late: {
    key: 'exam_late', label: '시험 지각', tags: ['평가','불안','타이밍'],
    meaning: '평가 상황에서 준비/시간 관리 불안.',
    advice: '마감 전 체크리스트 3개 정의.',
  },
  teacher: {
    key: 'teacher', label: '선생님/교사', tags: ['권위','학습','기준'],
    meaning: '기준/학습/권위와의 관계 점검.',
    advice: '배울 점 1개 적고 오늘 적용.',
  },
  classroom: {
    key: 'classroom', label: '교실', tags: ['학습','집단','평가'],
    meaning: '학습 환경/평가/사회적 비교.',
    advice: '오늘 배운 1가지를 실천으로 연결.',
  },
  stage_freeze: {
    key: 'stage_freeze', label: '무대에서 얼어붙음', tags: ['표현불능','불안','평가'],
    meaning: '표현 마비/평가 공포.',
    advice: '핵심 문장 1개를 소리내어 3번.',
  },
  phone_lost: {
    key: 'phone_lost', label: '핸드폰 분실', tags: ['정체성','연결','불안'],
    meaning: '연결/정체성 수단의 상실 불안.',
    advice: '중요 연락처/2FA 백업 점검.',
  },
  phone_battery: {
    key: 'phone_battery', label: '배터리 1%', tags: ['에너지','불안','준비'],
    meaning: '자원 고갈/준비 부족 신호.',
    advice: '오늘 에너지 채우기/예비 플랜 1개.',
  },
  password_forgot: {
    key: 'password_forgot', label: '비밀번호 잊음', tags: ['접근','안전','긴장'],
    meaning: '접근권·안전/기억의 이슈.',
    advice: '패스워드/백업/2FA 점검 10분.',
  },
  login_failed: {
    key: 'login_failed', label: '로그인 실패', tags: ['접근','정체성','불안'],
    meaning: '정체성/접근 실패 불안.',
    advice: '복구 루트와 백업 코드 관리.',
  },
  cloud_sync_lost: {
    key: 'cloud_sync_lost', label: '동기화 끊김', tags: ['데이터','연결','위험'],
    meaning: '데이터/연결 손실 가능성.',
    advice: '백업/동기화 상태 점검 10분.',
  },
  file_deleted: {
    key: 'file_deleted', label: '파일 삭제', tags: ['손실','정리','경고'],
    meaning: '손실/정리/종결의 신호.',
    advice: '중요 폴더 스냅샷 백업 즉시.',
  },
  storage_full: {
    key: 'storage_full', label: '용량 부족', tags: ['과부하','정리','지연'],
    meaning: '과부하/정리 지연.',
    advice: '공간 정리 10분 + 보관 정책 결정.',
  },
  alarm_missed: {
    key: 'alarm_missed', label: '알람 놓침', tags: ['타이밍','지각','관리'],
    meaning: '타이밍 관리 이슈.',
    advice: '리마인더/알람 이중화 설정.',
  },
  quarantine: {
    key: 'quarantine', label: '격리', tags: ['건강','분리','회복'],
    meaning: '건강/분리/회복 필요.',
    advice: '의료 조언/대기 루틴 준비.',
  },
  cough: {
    key: 'cough', label: '기침', tags: ['증상','건강','불편'],
    meaning: '건강 증상 인지.',
    advice: '수분/휴식/의료 상담 고려.',
  },
  fever: {
    key: 'fever', label: '발열', tags: ['증상','건강','회복'],
    meaning: '회복/휴식 신호.',
    advice: '수면 30분 보강 + 수분.',
  },
  meal: {
    key: 'meal', label: '식사', tags: ['양육','교류','에너지'],
    meaning: '양육/교류/에너지 보충.',
    advice: '오늘 식사 질을 한 단계 개선.',
  },
  ancestor_visit: {
    key: 'ancestor_visit', label: '조상/선조 방문', tags: ['기원','가치','연결'],
    meaning: '근원 가치 회수/통합.',
    advice: '내 가치 3줄을 다시 쓰고 선택을 정렬.',
  },
  president_meeting: {
    key: 'president_meeting', label: '대통령/권위자 만남', tags: ['권위','사회','의제'],
    meaning: '개인 의제 vs 사회/권위 무대의 긴장.',
    advice: '핵심 의제를 1줄로 명확화.',
  },
  high_building: {
    key: 'high_building', label: '높은 건물', tags: ['야망','리스크','전망'],
    meaning: '야망/전망/리스크 감지.',
    advice: '리스크 완충장치 1개 준비.',
  },
  window: {
    key: 'window', label: '창문', tags: ['관점','경계','통풍'],
    meaning: '관점/경계/환기의 상징.',
    advice: '새 관점 1개를 받아들이기.',
  },
  door: {
    key: 'door', label: '문', tags: ['경계','출입','전환'],
    meaning: '경계/출입/전환의 포인트.',
    advice: '닫을 문 1개/열 문 1개 정하기.',
  },
  key_item: {
    key: 'key_item', label: '열쇠', tags: ['접근','해결','자원'],
    meaning: '접근/해결의 힌트.',
    advice: '잠긴 문제의 열쇠 요소 1개 찾기.',
  },
  luggage_lost: {
    key: 'luggage_lost', label: '짐 분실', tags: ['정체성','소유','불안'],
    meaning: '정체성/과거/자원 손실 불안.',
    advice: '필수품 목록과 백업 계획 작성.',
  },
  stairs_fall: {
    key: 'stairs_fall', label: '계단에서 넘어짐', tags: ['실수','리스크','주의'],
    meaning: '작은 실수/주의 신호.',
    advice: '속도를 낮추고 난간 잡기(안전 강화).',
  },
  beach: { key: 'beach', label: '해변', tags: ['감정','경계','휴식'], meaning: '감정(바다)과 땅(현실)의 경계에서 휴식/전환.', advice: '짧은 산책과 물가 소리로 마음을 정화.' },
  island: { key: 'island', label: '섬', tags: ['고립','자립','안식'], meaning: '고립감/자립/안식의 양면.', advice: '혼자만의 회복시간 20분 확보.' },
  desert: { key: 'desert_i', label: '사막', tags: ['고갈','인내','탐색'], meaning: '자원 고갈/의미 탐색의 여정.', advice: '핵심 에너지원을 1개 보강.' },
  rainbow: { key: 'rainbow', label: '무지개', tags: ['희망','전환','화해'], meaning: '폭풍 뒤의 희망/화해 신호.', advice: '감사 1문장 기록 + 작은 축하.' },
  sunrise: { key: 'sunrise', label: '해돋이/일출', tags: ['새시작','에너지'], meaning: '새로운 시작/활력 재충전.', advice: '아침 루틴 10분 재개.' },
  sunset: { key: 'sunset', label: '일몰', tags: ['종결','정리','회상'], meaning: '종결/정리/되돌아봄의 시간.', advice: '오늘 끝낼 일 1개 종결.' },
  eclipse: { key: 'eclipse', label: '일식/월식', tags: ['전환','불확실','심층'], meaning: '빛의 가림=정보 부족/전환 신호.', advice: '결정 보류 후 정보 3개 수집.' },
  volcano: { key: 'volcano_i', label: '화산', tags: ['폭발','압력','변화'], meaning: '누적 압력의 폭발/변화의 시작.', advice: '감정 방출 루틴(운동/기록) 10분.' },
  wind: { key: 'wind', label: '강풍', tags: ['변화','불안정','정리'], meaning: '변화 바람/불안정성.', advice: '지지 구조(사람/도구) 1개 확보.' },
  forest_lost: { key: 'forest_lost', label: '숲에서 길 잃음', tags: ['혼란','탐색','인내'], meaning: '방향 상실/탐색의 필요.', advice: '목표 1개만 남기고 나머지 보류.' },
  cave: { key: 'cave', label: '동굴', tags: ['내면','은신','탐색'], meaning: '내면 심층/숨은 자원 탐색.', advice: '혼자 있는 시간에 질문 3개를 적기.' },
  temple: { key: 'temple', label: '사찰/절', tags: ['의식','정화','관조'], meaning: '의식/정화/관조의 공간.', advice: '짧은 명상 5분 + 호흡 3회.' },
  church: { key: 'church', label: '교회', tags: ['의지','공동체','규범'], meaning: '의지/공동체/규범 확인.', advice: '지지 인물 1명에게 연락.' },
  market: { key: 'market', label: '시장/장터', tags: ['교류','자원','혼잡'], meaning: '교류/자원 교환/과부하.', advice: '할 일 1개만 선택해 실행.' },
  office: { key: 'office', label: '사무실', tags: ['일','성과','규율'], meaning: '성과/규율/경계.', advice: '오늘의 최소 성과 1줄 정의.' },
  hospital_visit: { key: 'hospital_visit', label: '병원 방문', tags: ['치유','점검','불안'], meaning: '치유/검진 필요 신호.', advice: '증상/질문 3개를 메모.' },
  cemetery_visit: { key: 'cemetery_visit', label: '묘지 방문', tags: ['종결','애도','기억'], meaning: '종결/애도/기억 정리.', advice: '끝낼 일 1건 종결 선언.' },
  interview: { key: 'interview', label: '면접', tags: ['평가','표현','불안'], meaning: '평가/표현의 공식 장면.', advice: 'STAR 구조로 1분 답변 준비.' },
  graduation: { key: 'graduation', label: '졸업', tags: ['완료','전환','성취'], meaning: '완료/전환의 의식.', advice: '성과 3개 기록 + 다음 단계 정의.' },
  wedding: { key: 'wedding', label: '결혼식', tags: ['합의','관계','전환'], meaning: '합의/약속/전환의 의식.', advice: '합의할 한 줄 원칙을 적기.' },
  funeral: { key: 'funeral', label: '장례식', tags: ['종결','애도','정리'], meaning: '종결/애도/정리.', advice: '보내줄 것 1개 선택.' },
  birth: { key: 'birth', label: '출산', tags: ['탄생','새시작','책임'], meaning: '새로운 가능성/책임의 탄생.', advice: '새 아이디어 씨앗 1개 이름 붙이기.' },
  theft: { key: 'theft_i', label: '도둑/도난', tags: ['손실','경계','불안'], meaning: '손실/경계 강화 필요.', advice: '보안/프라이버시 설정 점검 10분.' },
  police: { key: 'police_i', label: '경찰', tags: ['규범','안전','통제'], meaning: '규범/안전/통제.', advice: '내 규칙 1개를 오늘 지키기.' },
  prison_cell: { key: 'prison_cell', label: '감옥/수감', tags: ['제한','속박','경계'], meaning: '제한/속박/경계 재설정.', advice: '스스로 만든 제약 1개 해제.' },
  bridge_cross: { key: 'bridge_cross', label: '다리 건넘', tags: ['전환','연결','결단'], meaning: '전환/연결/결단.', advice: '건널 다리 1개를 정해 실행.' },
  tunnel_dark: { key: 'tunnel_dark', label: '어두운 터널', tags: ['불확실','인내','집중'], meaning: '불확실 구간 통과.', advice: '노이즈 제거 25분 집중.' },
  river_cross: { key: 'river_cross', label: '강 건너기', tags: ['전환','결심','위험'], meaning: '전환/결심/리스크 인지.', advice: '대체 경로 1개 마련.' },
  mountain_peak: { key: 'mountain_peak', label: '산 정상', tags: ['목표','성취','전망'], meaning: '목표/전망/성취.', advice: '최상위 목표 1개 재정의.' },
  avalanche: { key: 'avalanche', label: '눈사태', tags: ['과부하','급변','경고'], meaning: '과부하/급변 리스크.', advice: '속도 20% 감속 + 완충장치.' },
  drowning_near: { key: 'drowning_near', label: '물에 빠질 뻔', tags: ['감정과부하','위험','경고'], meaning: '감정 과부하 경고.', advice: '즉시 휴식/자극 차단 15분.' },
  ship: { key: 'ship', label: '배/선박', tags: ['여정','집단','감정'], meaning: '감정의 바다 위 여정/집단.', advice: '항로/목표 1개 재설정.' },
  airplane_delay: { key: 'airplane_delay', label: '비행기 지연', tags: ['지연','전환','기대'], meaning: '전환 지연/기대 조정.', advice: '대기 루틴(읽기/정리) 10분.' },
  luggage_heavy: { key: 'luggage_heavy', label: '짐이 무거움', tags: ['과부하','책임','정리'], meaning: '책임/짐 과부하.', advice: '필수/선택 분리 후 내려놓기 1개.' },
  shoes_missing: { key: 'shoes_missing', label: '신발 분실', tags: ['기반','이동','정체성'], meaning: '기반/이동 준비 미비.', advice: '기본 도구/환경 점검.' },
  clothes_torn: { key: 'clothes_torn', label: '옷이 찢어짐', tags: ['수치','노출','경계'], meaning: '경계/자기상 노출 불안.', advice: '경계 문장 1개 선언.' },
  wallet_lost: { key: 'wallet_lost', label: '지갑 분실', tags: ['재정','정체성','손실'], meaning: '재정/신원 손실 불안.', advice: '지출/계정 보안 점검 10분.' },
  watch_broken: { key: 'watch_broken', label: '시계 고장', tags: ['타이밍','우선순위','지연'], meaning: '시간/우선순위 관리 이슈.', advice: '3가지 우선 순위만 남기기.' },
  letter_unread: { key: 'letter_unread', label: '편지/읽지 않음', tags: ['메시지','미해결','연결'], meaning: '메시지/감정 미해결.', advice: '미회신 1건 즉시 처리.' },
  camera_fail: { key: 'camera_fail', label: '카메라 고장', tags: ['기록','시선','기술'], meaning: '기록/시선 문제.', advice: '종이/텍스트로 대체 기록 5분.' },
  singing: { key: 'singing', label: '노래', tags: ['표현','자유','감정'], meaning: '표현/감정 방출.', advice: '짧은 발성/호흡으로 긴장 완화.' },
  dancing: { key: 'dancing', label: '춤', tags: ['자유','리듬','에너지'], meaning: '자유/리듬/에너지.', advice: '3분 몸풀기/산책.' },
  crying: { key: 'crying', label: '울음', tags: ['정화','표현','감정'], meaning: '정화/감정 방출.', advice: '감정 라벨 1개 적기.' },
  laughing_out: { key: 'laughing_out', label: '크게 웃음', tags: ['긍정','해방','에너지'], meaning: '긍정/해방/에너지.', advice: '감사 1문장 기록.' },
  fight: { key: 'fight', label: '싸움/격투', tags: ['갈등','경계','표현'], meaning: '갈등/경계/표현.', advice: 'I-메시지 3줄로 재구성.' },
  chase_monster: { key: 'chase_monster', label: '괴물에게 쫓김', tags: ['회피','불안','그림자'], meaning: '그림자/회피 주제.', advice: '도망친 과제 25분 착수.' },
  hiding_closet: { key: 'hiding_closet', label: '옷장에 숨음', tags: ['자기보호','회피','경계'], meaning: '자기보호/과도한 회피.', advice: '안전 행동 1개 + 작은 노출 1개.' },
  speaking_fail: { key: 'speaking_fail', label: '말이 안 나옴', tags: ['표현','불안','평가'], meaning: '표현 마비.', advice: '핵심 문장 1개 소리내어 3회.' },
  teeth_clean: { key: 'teeth_clean', label: '이 닦기', tags: ['정리','표현','이미지'], meaning: '표현/이미지 정리 의지.', advice: '한 문장 요약을 정제.' },
  haircut: { key: 'haircut', label: '머리 자르기', tags: ['변화','정체성','리셋'], meaning: '정체성/변화/리셋.', advice: '작업환경 10분 리셋.' },
  mirror_shatter: { key: 'mirror_shatter', label: '거울 깨짐', tags: ['자아상','변화','경고'], meaning: '자아상 변화/경고.', advice: '자기서술 3문장 새로 쓰기.' },
  phone_call: { key: 'phone_call_i', label: '전화', tags: ['연결','소통','요청'], meaning: '연결/소통/요청.', advice: '중요 1통 바로 연락.' },
  message_spam: { key: 'message_spam', label: '스팸 메시지', tags: ['노이즈','경계','스팸'], meaning: '노이즈/경계 필요.', advice: '알림 정리/필터 10분.' },
  notifications_overflow: { key: 'notifications_overflow', label: '알림 폭주', tags: ['과부하','집중','노이즈'], meaning: '과부하/집중 저하.', advice: '알림 묶음/요약 설정.' },
  dm_left_on_read: { key: 'left_on_read', label: '읽씹', tags: ['관계','불안','경계'], meaning: '관계 경계/불안.', advice: '주의 전환/셀프케어 10분.' },
  spam_dm: { key: 'spam_dm', label: 'DM 스팸', tags: ['스팸','경계','프라이버시'], meaning: '스팸/프라이버시 경계.', advice: '차단/신고/필터 강화.' },
  video_call_lag: { key: 'video_call_lag', label: '화상통화 지연', tags: ['소통','품질','집중'], meaning: '소통 품질/집중 이슈.', advice: '아젠다/품질 설정 사전 합의.' },
  screen_cracked: { key: 'screen_cracked', label: '화면 깨짐', tags: ['손상','눈피로','집중'], meaning: '손상/눈 피로/집중 저하.', advice: '스크린타임 단축/조도 조절.' },
  boss_criticism: { key: 'boss_criticism', label: '상사 질책', tags: ['직장','평가','스트레스'], meaning: '평가 스트레스/학습 기회.', advice: '사실-영향-다음 행동 3줄 요약.' },
  coworker_conflict: { key: 'coworker_conflict', label: '동료 갈등', tags: ['협업','경계','갈등'], meaning: '협업 규칙/경계 재설정.', advice: '역할/시간/결과 3줄 작업계약.' },
  partner_argument: { key: 'partner_argument_i', label: '연인과 말다툼', tags: ['관계','소통','경계'], meaning: '욕구/경계 충돌.', advice: 'I-메시지 3줄 작성.' },
  jealousy_scene: { key: 'jealousy_scene_i', label: '질투 장면', tags: ['관계','신뢰','통제'], meaning: '신뢰/통제 이슈.', advice: '경계 회복/요청을 명확히.' },
  ring_found: { key: 'ring_found', label: '반지 발견', tags: ['가치','약속','회복'], meaning: '가치/약속 회복.', advice: '소중한 약속 1개를 재선언.' },
  baby_laugh: { key: 'baby_laugh', label: '아기 웃음', tags: ['희망','새시작','기쁨'], meaning: '새 가능성의 기쁨.', advice: '씨앗 프로젝트에 10분 투자.' },
  cat_scratched: { key: 'cat_scratched', label: '고양이에게 할큄', tags: ['경계','자율','거리'], meaning: '자율/거리 조절 신호.', advice: '경계 존중 문장 1개 작성.' },
  dog_follow: { key: 'dog_follow', label: '개가 따라옴', tags: ['충성','보호','연결'], meaning: '지지/보호 신호.', advice: '지지 인물에게 감사 1문장.' },
  snake_bite: { key: 'snake_bite', label: '뱀에 물림', tags: ['경고','변화','치유'], meaning: '변화 경고/치유 주제.', advice: '버릴 것 1개 실제로 버리기.' },
  spider_web: { key: 'spider_web', label: '거미줄', tags: ['연결','구속','섬세'], meaning: '연결망/구속/섬세함.', advice: '얽힌 일 분해/순서화.' },
  tiger_roar: { key: 'tiger_roar', label: '호랑이 포효', tags: ['힘','분노','리더십'], meaning: '억눌린 힘/리더십 호출.', advice: '입장 1번 명확히 표명.' },
  bear_sleep: { key: 'bear_sleep', label: '곰 겨울잠', tags: ['휴식','회복','대기'], meaning: '휴식/회복/대기.', advice: '수면 30분 보강.' },
  // ── Domain-level generic symbols (fallback coverage) ──
  domain_relationship: {
    key: 'domain_relationship', label: '관계(연인/가족/친구)', tags: ['관계','소통','경계'],
    meaning: '관계 전반의 신호. 소통/경계/기대가 얽힌 주제를 반영합니다.',
    advice: 'I-메시지 3줄(사실-느낌-요구)을 적고 전달 전 소리내어 읽기.',
  },
  domain_health: {
    key: 'domain_health', label: '건강/몸 신호', tags: ['건강','회복','점검'],
    meaning: '몸의 피로/증상/회복 욕구를 반영합니다.',
    advice: '수면·빛·물·움직임 중 2가지를 오늘 10분 보강.',
  },
  domain_work: {
    key: 'domain_work', label: '일/성과/직장', tags: ['일','성과','규칙'],
    meaning: '성과/책임/규칙 이슈. 우선순위와 경계 재정의 신호.',
    advice: '최상위 우선순위 1개만 남기고 25분 집중.',
  },
  domain_school: {
    key: 'domain_school', label: '학교/학습/평가', tags: ['학습','평가','성장'],
    meaning: '학습·평가 압박과 성장통의 신호.',
    advice: '모의답 3문장 + 합격기준을 나만의 문장으로 낮추기.',
  },
  domain_fear: {
    key: 'domain_fear', label: '공포/추격/괴물', tags: ['두려움','회피','그림자'],
    meaning: '두려움/회피/그림자 주제. 도망친 과제가 은유될 수 있음.',
    advice: '4-7-8 호흡 3회 후 10분 작은 노출 실행.',
  },
  domain_travel: {
    key: 'domain_travel', label: '이동/여행/전환', tags: ['전환','방향','리듬'],
    meaning: '전환의 문턱과 리듬 조정 신호.',
    advice: '필수 요건 체크 3개 + 대기 루틴 10분.',
  },
  domain_home: {
    key: 'domain_home', label: '집/공간/경계', tags: ['자아','안정','경계'],
    meaning: '자아 구조/경계/안정성 점검 신호.',
    advice: '작업공간 10분 정리 + 경계 문장 1개 선언.',
  },
  domain_money: {
    key: 'domain_money', label: '돈/지출/가치', tags: ['재정','가치','안전'],
    meaning: '재정/가치/안전에 대한 신호.',
    advice: '오늘 지출 3항목 점검 + 비상자금 확인.',
  },
  domain_digital: {
    key: 'domain_digital', label: '디지털/연결/보안', tags: ['연결','보안','노이즈'],
    meaning: '디지털 연결/노이즈/보안 이슈.',
    advice: '알림 정리 10분 + 2FA/백업 점검.',
  },
  domain_nature: {
    key: 'domain_nature', label: '자연/기상/환경', tags: ['자연','정화','변화'],
    meaning: '자연/기상 패턴을 통한 정화/변화 신호.',
    advice: '자연 노출 10분 + 물 한 잔.',
  },
  unknown_generic: {
    key: 'unknown_generic', label: '일반(해석 보조)', tags: ['메타','정리','관찰'],
    meaning: '특정 상징이 없을 때도 감정/색/행동 단서로 의미를 구성할 수 있습니다.',
    advice: '감정 1개 라벨링 → 연결된 장면 3문장 기록 → 10분 실험 1개 실행.',
  },
  // ── Generic categories for broad coverage ──
  animal_pet: { key: 'animal_pet', label: '반려동물(개/고양이 등)', tags: ['관계','보호','친밀'], meaning: '보호/친밀/충성/자율 테마.', advice: '지지/경계 균형을 한 줄로 점검.' },
  animal_wild: { key: 'animal_wild', label: '야생동물', tags: ['본능','힘','경계'], meaning: '본능/힘/경계의 호출.', advice: '억눌린 힘을 안전하게 표출할 작은 행동.' },
  bird_generic: { key: 'bird_generic', label: '새/비행', tags: ['자유','소식','관점'], meaning: '자유/관점 상승/메시지.', advice: '문제를 3m 위 관점에서 다시 보기.' },
  fish_generic: { key: 'fish_generic', label: '물고기/바다생물', tags: ['무의식','감정','풍요'], meaning: '무의식/감정의 흐름.', advice: '물 한 잔 + 감정 라벨 1개.' },
  insect_generic: { key: 'insect_generic', label: '곤충', tags: ['불편','집요','섬세'], meaning: '사소해 보이지만 신경 쓰이는 요소.', advice: '미세 스트레스원을 1개 제거.' },
  vehicle_car: { key: 'vehicle_car', label: '자동차', tags: ['방향','통제','여정'], meaning: '방향성/통제/자율 이동.', advice: '이번 주 경로/목표를 3줄로 재정의.' },
  vehicle_bus: { key: 'vehicle_bus', label: '버스', tags: ['집단','리듬','타이밍'], meaning: '집단 리듬/타이밍.', advice: '기회/시간표 점검 + 리마인더.' },
  vehicle_train: { key: 'vehicle_train', label: '기차', tags: ['과정','전환','리듬'], meaning: '정해진 레일의 전환/과정 수용.', advice: '과정의 이점 3개 적기.' },
  vehicle_bike: { key: 'vehicle_bike', label: '자전거', tags: ['균형','노력','자율'], meaning: '균형/노력/자율 이동.', advice: '균형을 위한 작은 연습 10분.' },
  vehicle_plane: { key: 'vehicle_plane', label: '비행기', tags: ['확장','높은관점','전환'], meaning: '확장/전환/높은 관점.', advice: '확장 목표 1개 미니실험.' },
  vehicle_ship: { key: 'vehicle_ship', label: '배/선박', tags: ['여정','감정','집단'], meaning: '감정의 바다 위 여정.', advice: '항로/대체경로 점검.' },
  building_home: { key: 'building_home', label: '집/주거', tags: ['자아','안정','경계'], meaning: '자기 경계/안정의 은유.', advice: '공간 10분 정리 + 경계 문장 1개.' },
  building_apartment: { key: 'building_apartment', label: '아파트', tags: ['생활','이웃','구조'], meaning: '생활 구조/이웃 관계.', advice: '생활 루틴 1개 최적화.' },
  building_office: { key: 'building_office', label: '사무실', tags: ['일','성과','규율'], meaning: '성과/규율/경계.', advice: '최소 성과 1줄 정의.' },
  building_school: { key: 'building_school', label: '학교', tags: ['학습','평가','성장'], meaning: '학습/평가/성장.', advice: '학습 15분 블록.' },
  building_hospital2: { key: 'building_hospital2', label: '병원', tags: ['치유','점검','불안'], meaning: '치유/검진 신호.', advice: '증상/질문 3개 메모.' },
  building_market: { key: 'building_market', label: '시장/마트', tags: ['교류','자원','혼잡'], meaning: '교류/자원/과부하.', advice: '필수만 고르고 실행.' },
  building_temple2: { key: 'building_temple2', label: '사찰/절', tags: ['의식','정화','관조'], meaning: '의식/정화/관조.', advice: '짧은 명상/호흡.' },
  building_church2: { key: 'building_church2', label: '교회', tags: ['의지','공동체','규범'], meaning: '의지/공동체/규범.', advice: '지지 인물에게 연락.' },
  object_phone: { key: 'object_phone', label: '핸드폰/스마트폰', tags: ['연결','정체성','안전'], meaning: '연결/정체성/접근.', advice: '백업/2FA/비번 점검 10분.' },
  object_laptop: { key: 'object_laptop', label: '노트북/컴퓨터', tags: ['작업','기록','연결'], meaning: '작업/기록/연결 도구.', advice: '작업환경 정리 10분.' },
  object_camera: { key: 'object_camera', label: '카메라', tags: ['시선','기록','기술'], meaning: '시선/기록/기술.', advice: '대체 기록(텍스트/음성) 시도.' },
  object_book: { key: 'object_book', label: '책', tags: ['학습','기록','영감'], meaning: '학습/기록/영감.', advice: '요약 3문장 기록.' },
  object_pen: { key: 'object_pen', label: '펜/연필', tags: ['표현','계획','기록'], meaning: '표현/계획/기록.', advice: '오늘 3문장 쓰기.' },
  object_key2: { key: 'object_key2', label: '열쇠', tags: ['접근','해결','보안'], meaning: '접근/해결의 힌트.', advice: '열쇠 요소 1개 찾기.' },
  object_wallet2: { key: 'object_wallet2', label: '지갑/카드', tags: ['재정','정체성','접근'], meaning: '재정/정체성/접근.', advice: '지출/보안 점검.' },
  object_bag: { key: 'object_bag', label: '가방', tags: ['짐','준비','정리'], meaning: '짐/준비/정리.', advice: '짐에서 뺄 것 1개.' },
  object_clothes: { key: 'object_clothes', label: '옷/의류', tags: ['자기상','경계','표현'], meaning: '자기상/경계/표현.', advice: '편안+표현을 만족하는 선택 1개.' },
  object_jewelry: { key: 'object_jewelry', label: '반지/목걸이', tags: ['가치','약속','자기상'], meaning: '가치/약속/자기상.', advice: '가치 한 줄 선언.' },
  food_generic: { key: 'food_generic', label: '음식', tags: ['양육','에너지','교류'], meaning: '양육/에너지/교류.', advice: '식사 질 1단계 개선.' },
  drink_water: { key: 'drink_water', label: '물 마시기', tags: ['정화','회복','기초'], meaning: '정화/회복/기초.', advice: '물 한 잔 + 호흡.' },
  drink_alcohol: { key: 'drink_alcohol', label: '술', tags: ['완화','회피','교류'], meaning: '완화/회피/교류.', advice: '분량 제한/대체 회복 루틴.' },
  document_passport: { key: 'document_passport', label: '여권/신분증/티켓', tags: ['자격','접근','전환'], meaning: '자격/접근/전환.', advice: '필수 서류 체크 3개.' },
  body_head: { key: 'body_head', label: '머리/두통', tags: ['인지','피로','스트레스'], meaning: '인지/피로/스트레스.', advice: '빛/수면/수분 보강.' },
  body_hand: { key: 'body_hand', label: '손', tags: ['행동','기술','접촉'], meaning: '행동/기술/접촉.', advice: '손으로 3분 행동.' },
  body_foot: { key: 'body_foot', label: '발', tags: ['기반','이동','안정'], meaning: '기반/이동/안정.', advice: '동선 최적화 1건.' },
  injury_wound: { key: 'injury_wound', label: '상처/다침', tags: ['손상','회복','경고'], meaning: '손상/회복/경고.', advice: '자기돌봄 10분 + 필요시 상담.' },
};
